### GET SITE PAYROLLS (TEST)
GET http://localhost:5000/api/payroll/site
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjA4YjgxZmRjMWEyMWUxMjc2MzFkNGUiLCJ0eXBlIjoxLCJzaXRlIjoiNjIwOGI4MWVkYzFhMjFlMTI3NjMxZDRjIiwiaWF0IjoxNjQ4NDUzOTQ5fQ.R6V_CiAEQsDKxKNvdA5h2z-x-l9ZCzwYKze0TLI1t7s

### GET SITE PAYROLLS (SAIT)
GET http://localhost:5000/api/payroll/site
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjE4MzJjZGU4MWRkNWVlZGU1MGFjYTgiLCJ0eXBlIjoxLCJzaXRlIjoiNjIxODMyY2RlODFkZDVlZWRlNTBhY2E2IiwiaWF0IjoxNjQ3MzIzNTQxfQ.S8z1vKL6xekbYU90XSVsu9q_Gs8wYrbXmkUICmpd_JU

### GET USER PAYROLLS
GET http://localhost:5000/api/payroll/user
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjBjYWIwMGUwNWVjYzY0YmNkZjk4ZjYiLCJ0eXBlIjoyLCJzaXRlIjoiNjIwOGI4MWVkYzFhMjFlMTI3NjMxZDRjIiwiaWF0IjoxNjQ4NDU1MDE1fQ.LTpSCW3iPtTV-3dAVawNvqq9xR1LKym-iZ56ggrtnzw

### GET SITE PAYROLL BY MONTH
GET http://localhost:5000/api/payroll/site/2022-02
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjA4YjgxZmRjMWEyMWUxMjc2MzFkNGUiLCJ0eXBlIjoxLCJzaXRlIjoiNjIwOGI4MWVkYzFhMjFlMTI3NjMxZDRjIiwiaWF0IjoxNjQ2NzU4MDUzfQ.UE2F4eGybDngdJdcuQXxTgb7fCPnXmLvxvAAHiJjK4Y

### GET USER PAYROLL BY MONTH
GET http://localhost:5000/api/payroll/user/2022-02
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MjA4YjgxZmRjMWEyMWUxMjc2MzFkNGUiLCJ0eXBlIjoxLCJzaXRlIjoiNjIwOGI4MWVkYzFhMjFlMTI3NjMxZDRjIiwiaWF0IjoxNjQ2NzU4MDUzfQ.UE2F4eGybDngdJdcuQXxTgb7fCPnXmLvxvAAHiJjK4Y
